<?php
/**
 * Created by PhpStorm.
 * User: Slowbro
 * Date: 16/12/5
 * Time: 上午10:33
 */

namespace frontend\controllers;


use common\models\UserPrize;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use Yii;
use common\models\Prize;

class PrizeController extends Controller
{


    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    public function actionGetprize(){//获取抽奖结果接口
        $user_id = Yii::$app->user->identity->getMenb();
        //TODO dose the user have enough money to have a lottery

        $prize = new Prize();
        $prize_array = $prize->get_as_arrays();//    'id,name,sort,proportion,limit_number'

        $result = $this->prize_result($prize_array); //id , total_number

        if($result['number'] == 0|| $result['id'] == 0)
        {
            return json_encode(array('code'=>0,'message'=>'中奖人数已满'));
        }//如果中奖人数满则返回提示语

        $prize_result = $prize->get_by_id($result['id']);
        if(isset($prize_result))
        {
            $user_prize = new UserPrize();
            if($user_prize->add_log($user_id,$prize_result))
            {
                $prize_result['total_number'] = $result['total_number'];

                return json_encode($prize_result);
            }
            else
            {
                return json_encode(array('code'=>0,'message'=>'记录数据库时出错，请联系客服'));
//                return json_encode(array('code'=>0,'message'=>'中奖人数已满'));
            }
        }
        else
        {
            return json_encode(array('code'=>0,'message'=>'错误的奖品信息，请重新刷新'));
        }
    }


    public function prize_result($array){//获取抽奖结果函数，返回一个奖品的id和抽奖的旋转
//        $render_array = ArrayHelper::map($array,'proportion','limit_number','id');

        $total_number = 0;
        foreach ($array as $key => $value){
            $total_number += $value['proportion'];
        }

        $return = array('total_number'=>$total_number);//返回的数据
        $number = mt_rand(1,$total_number);//随机数
        $result = 0;//结果，最后获得的奖品
        $id = 0;
        $level_number = 0;

        foreach ($array as $key => $value){
            if($number<=$level_number+$value['proportion'])
            {
                $is_enough = UserPrize::is_enough($value['limit_number'],$value['id']);
                if($is_enough)
                {
                    $number += $value['proportion'];
                    $level_number += $value['proportion'];
                    continue;
                }
                else
                {
                    $result = $key+1;
                    $id = $value['id'];
                    break;
                }
            }
            else
            {
                $level_number += $value['proportion'];
//                $total_number -= $value;
            }
        }
        $return['number'] = $result;//第几等奖
        $return['id'] = $id;
        return $return;
    }

    public function actionList(){
        $prize = new Prize();
        $lists = $prize->get_as_arrays();
        return json_encode($lists);
    }

    public function actionTest(){
        $number = UserPrize::is_enough(1,1);
        var_dump($number);
    }
}